resources:
  - ../../../base/hello-world

labels:
  - pairs:
      env: staging
    includeTemplates: true
    includeSelectors: true
namespace: staging


patches:
  - path: inject-secret.yaml
    target:
      kind: Deployment