resources:
  - ../../../base/hello-world

labels:
  - pairs:
      env: staging
    includeTemplates: true
    includeSelectors: true
namespace: staging

images:
  - name: tiendat1011/uv-fastapi
    newTag: f87a1557


patches:
  - path: inject-secret.yaml
    target:
      kind: Deployment