resources:
  - ../../../base/hello-world

labels:
  - pairs:
      env: prod
    includeTemplates: true
    includeSelectors: true
namespace: prod

images:
  - name: tiendat1011/uv-fastapi
    newTag: f87a1557

patches:
  - path: inject-secret.yaml
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31600
    target:
      kind: Service
