resources:
  - ../../../base

labels:
  - pairs:
      env: prod
    includeTemplates: true
    includeSelectors: true
namespace: prod

patches:
  - path: inject-secret.yaml
    target:
      kind: Deployment